# Generated by Django 5.1.8 on 2025-04-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignees',
            options={'verbose_name': 'Assignees'},
        ),
    ]
