# Generated by Django 5.1.8 on 2025-04-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfiles',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='Task.task'),
        ),
    ]
