# Generated by Django 5.1.8 on 2025-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_task_issue_type_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
