# Generated by Django 5.1.8 on 2025-05-15 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_assignees_options'),
        ('Task', '0010_alter_task_customer_id_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='task',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_issue', to='Task.issue', verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_priority', to='Task.priority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_sector', to='Task.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_source', to='Task.source', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='Task.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_support_type', to='Task.support', verbose_name='Support Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_update_task', to=settings.AUTH_USER_MODEL, verbose_name='Update User'),
        ),
        migrations.CreateModel(
            name='TaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(blank=True, max_length=30, null=True, verbose_name='Router')),
                ('rj45', models.IntegerField(verbose_name='RJ45 Connectors')),
                ('outdoor_cable', models.IntegerField(verbose_name='Outdoor Drop Cable')),
                ('indoor_cable', models.IntegerField(verbose_name='Indoor Drop Cable')),
                ('cat6_indoor_cable', models.IntegerField(verbose_name='CAT6 Indoor Cable')),
                ('patchcode_apc', models.IntegerField(verbose_name='Patch Code LC/APC/-SC/APC')),
                ('patchcode_upc', models.IntegerField(verbose_name='Patch Code LC/APC/-SC/UPC')),
                ('loaded_atb', models.IntegerField(verbose_name='Loaded ATB')),
                ('empty_atb', models.IntegerField(verbose_name='Empty ATB')),
                ('splitter_8', models.IntegerField(verbose_name='Splitter 1 by 8')),
                ('splitter_4', models.IntegerField(verbose_name='Splitter 1 by 4')),
                ('splitter_2', models.IntegerField(verbose_name='Splitter 1 by 2')),
                ('splitter_16', models.IntegerField(verbose_name='Splitter 1 by 16')),
                ('fat_4', models.IntegerField(verbose_name='FAT 1 by 4')),
                ('fat_8', models.IntegerField(verbose_name='FAT 1 by 8')),
                ('router_charger', models.IntegerField(verbose_name='Router Charger')),
                ('poe', models.IntegerField(verbose_name='POE Adapter')),
                ('sleeves', models.IntegerField(verbose_name='Sleeves')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_material', to='Task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignee_material', to='Profile.assignees')),
            ],
        ),
    ]
