# Generated by Django 5.1.8 on 2025-05-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_alter_task_created_by_alter_task_issue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaterial',
            name='cat6_indoor_cable',
            field=models.IntegerField(blank=True, null=True, verbose_name='CAT6 Indoor Cable'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='empty_atb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Empty ATB'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='fat_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='FAT 1 by 4'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='fat_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='FAT 1 by 8'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='indoor_cable',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indoor Drop Cable'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='loaded_atb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Loaded ATB'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='outdoor_cable',
            field=models.IntegerField(blank=True, null=True, verbose_name='Outdoor Drop Cable'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='patchcode_apc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patch Code LC/APC/-SC/APC'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='patchcode_upc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patch Code LC/APC/-SC/UPC'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='poe',
            field=models.IntegerField(blank=True, null=True, verbose_name='POE Adapter'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='rj45',
            field=models.IntegerField(blank=True, null=True, verbose_name='RJ45 Connectors'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='router_charger',
            field=models.IntegerField(blank=True, null=True, verbose_name='Router Charger'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='sleeves',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sleeves'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='splitter_16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Splitter 1 by 16'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='splitter_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Splitter 1 by 2'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='splitter_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Splitter 1 by 4'),
        ),
        migrations.AlterField(
            model_name='taskmaterial',
            name='splitter_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Splitter 1 by 8'),
        ),
    ]
