# Generated by Django 5.1.8 on 2025-05-17 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_alter_taskmaterial_cat6_indoor_cable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaterial',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
