# Generated by Django 5.1.8 on 2025-04-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_alter_taskfiles_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_issue', to='Task.issue', verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_priority', to='Task.priority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_source', to='Task.source', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='Task.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_support_type', to='Task.support', verbose_name='Support Type'),
        ),
    ]
